[package]
name = "arb-gnucash-importer"
version = "1.0.0"
authors = ["Ryan Bruno <ryanbruno506@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
log4rs = "1"